name: Build SNES ROM
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar gnupg

      - name: Bootstrap devkitPro pacman (adds dkp-pacman)
        run: |
          wget -q https://apt.devkitpro.org/install-devkitpro-pacman -O install-dkp.sh
          sudo bash install-dkp.sh
          echo "/opt/devkitpro/pacman/bin" >> $GITHUB_PATH

      - name: Cache devkitPro packages (speeds up later runs)
        uses: actions/cache@v4
        with:
          path: /opt/devkitpro/pacman/var/cache/pacman/pkg
          key: dkp-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: dkp-${{ runner.os }}-

      - name: Install pvsneslib
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --needed --noconfirm pvsneslib

      - name: Build advanced project
        run: |
          cd snes-pink-puff-adv
          make -j$(nproc)

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pink-puff-roms
          path: snes-pink-puff-adv/*.sfc
