name: Build SNES ROM

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install devkitPro SNES toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://apt.devkitpro.org/install-devkitpro-pacman | bash
          sudo dkp-pacman -Syu
          sudo dkp-pacman -S snes-dev

      - name: Build SNES ROM
        run: |
          # Replace with your actual build command if different
          # Example: If you use Makefile, replace with 'make'
          snescc -o output.snes main.c

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: snes-rom
          path: output.snes
