name: Build SNES ROM
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up MSYS2 on the Windows runner (no Docker, no apt)
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: >-
            wget
            tar
            unzip
            make

      # Add devkitPro pacman & pvsneslib inside MSYS2
      - name: Bootstrap devkitPro + pvsneslib
        shell: msys2 {0}
        run: |
          set -eux
          wget -q https://apt.devkitpro.org/install-devkitpro-pacman -O install-dkp.sh
          bash install-dkp.sh
          dkp-pacman -Syyu --noconfirm || true
          dkp-pacman -S --needed --noconfirm pvsneslib

      # Find your game folder even if it’s nested, or unzip it if you uploaded a zip
      - name: Locate/prepare sources
        id: locate
        shell: msys2 {0}
        run: |
          set -eux
          SRC=""
          if [ -d "snes-pink-puff-adv" ]; then
            SRC="snes-pink-puff-adv"
          elif [ -d "pink-puff-snes-repo/snes-pink-puff-adv" ]; then
            SRC="pink-puff-snes-repo/snes-pink-puff-adv"
          elif [ -f "snes-pink-puff-adv.zip" ]; then
            unzip -o snes-pink-puff-adv.zip
            SRC="snes-pink-puff-adv"
          elif [ -f "pink-puff-snes-repo/snes-pink-puff-adv.zip" ]; then
            unzip -o pink-puff-snes-repo/snes-pink-puff-adv.zip -d .
            SRC="snes-pink-puff-adv"
          else
            echo "::error::Could not find snes-pink-puff-adv (folder or zip) at repo root or inside pink-puff-snes-repo/"
            exit 2
          fi
          test -f "$SRC/Makefile" || { echo "::error::Missing Makefile in $SRC"; exit 3; }
          echo "SRC=$SRC" >> "$GITHUB_ENV"

      # Build with make inside MSYS2
      - name: Build ROM
        shell: msys2 {0}
        run: |
          set -eux
          cd "$SRC"
          make -j2

      # Publish the .sfc file
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pink-puff-roms
          path: '**/*.sfc'
