name: Build SNES ROM
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
         image: ghcr.io/devkitpro/devkitpro:latest  # GHCR, pinned tag

    steps:
      - uses: actions/checkout@v4

      # Accept either a top-level snes-pink-puff-adv/ or the same folder under pink-puff-snes-repo/
      - name: Locate sources
        id: locate
        run: |
          set -eux
          if [ -d "snes-pink-puff-adv" ]; then
            SRC="snes-pink-puff-adv"
          elif [ -d "pink-puff-snes-repo/snes-pink-puff-adv" ]; then
            SRC="pink-puff-snes-repo/snes-pink-puff-adv"
          else
            echo "::error::Missing snes-pink-puff-adv folder (either at repo root or inside pink-puff-snes-repo/)"
            exit 2
          fi
          test -f "$SRC/Makefile" || { echo "::error::$SRC/Makefile not found"; exit 3; }
          echo "SRC=$SRC" >> "$GITHUB_ENV"

      - name: Install pvsneslib (via devkitPro pacman)
        run: |
          set -eux
          dkp-pacman -Syyu --noconfirm || true
          dkp-pacman -S --needed --noconfirm pvsneslib || (sleep 5; dkp-pacman -S --needed --noconfirm pvsneslib)

      - name: Build ROM
        run: |
          set -eux
          cd "$SRC"
          make -j

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pink-puff-roms
          path: ${{ env.SRC }}/*.sfc
