name: Build SNES ROM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for snes-pink-puff-adv folder
      run: |
        if [ -d "snes-pink-puff-adv" ]; then
          SRC="snes-pink-puff-adv"
        elif [ -d "pink-puff-snes-repo/snes-pink-puff-adv" ]; then
          SRC="pink-puff-snes-repo/snes-pink-puff-adv"
        else
          echo "::error::Missing snes-pink-puff-adv folder (root or pink-puff-snes-repo/)"
          exit 2
        fi
        echo "SRC=$SRC" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git make

    - name: Install devkitPro and pvsneslib manually
      run: |
        # Install devkitPro (replace with latest instructions if needed)
        wget https://apt.devkitpro.org/install-devkitpro-pacman.sh
        chmod +x install-devkitpro-pacman.sh
        sudo ./install-devkitpro-pacman.sh
        # Install pvsneslib from source
        git clone https://github.com/alekmaul/pvsneslib.git
        cd pvsneslib
        make
        sudo make install
        cd ..

    - name: Build project
      run: |
        test -f "$SRC/Makefile" || { echo "::error::$SRC/Makefile not found"; exit 3; }
        make -C "$SRC"
