name: Build SNES ROM
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Use GHCR (more reliable than Docker Hub) and pin a tag
    container:
      image: ghcr.io/devkitpro/devkitpro:2024-07-05

    steps:
      - uses: actions/checkout@v4

      - name: Install pvsneslib
        run: |
          dkp-pacman -Syu --noconfirm || true
          dkp-pacman -S --needed --noconfirm pvsneslib

      - name: Build advanced project
        run: |
          cd snes-pink-puff-adv
          make -j

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pink-puff-roms
          path: snes-pink-puff-adv/*.sfc
