name: Build SNES ROM

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install snes-sdk
      run: |
        sudo apt-get update
        sudo apt-get install -y snes-sdk

    - name: Build SNES ROM
      run: |
        # Replace 'main.smc' with your actual source file and build command
        snescc -o output.snes main.c

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v4
      with:
        name: snes-rom
        path: output.snes
