name: Build SNES ROM
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/devkitpro/devkitpro:2024-07-05

    steps:
      - uses: actions/checkout@v4

      - name: Locate sources (handles nested or zipped)
        id: locate
        run: |
          set -eux
          echo "== repo tree =="
          find . -maxdepth 3 -print | sed 's#^\./##'
          SRC=""
          if [ -d "snes-pink-puff-adv" ]; then
            SRC="snes-pink-puff-adv"
          elif [ -d "pink-puff-snes-repo/snes-pink-puff-adv" ]; then
            SRC="pink-puff-snes-repo/snes-pink-puff-adv"
          elif [ -f "snes-pink-puff-adv.zip" ]; then
            unzip -o snes-pink-puff-adv.zip
            SRC="snes-pink-puff-adv"
          elif [ -f "pink-puff-snes-repo/snes-pink-puff-adv.zip" ]; then
            unzip -o pink-puff-snes-repo/snes-pink-puff-adv.zip -d .
            SRC="snes-pink-puff-adv"
          else
            echo "::error::Could not find snes-pink-puff-adv (folder or zip) at repo root or inside pink-puff-snes-repo/"
            exit 2
          fi
          test -f "$SRC/Makefile" || { echo "::error::Missing Makefile in $SRC"; exit 3; }
          echo "SRC=$SRC" >> "$GITHUB_ENV"

      - name: Install pvsneslib (with retry)
        run: |
          set -eux
          dkp-pacman -Syyu --noconfirm || true
          dkp-pacman -S --needed --noconfirm pvsneslib || (sleep 5; dkp-pacman -S --needed --noconfirm pvsneslib)

      - name: Build
        run: |
          set -eux
          cd "$SRC"
          make -j

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pink-puff-roms
          path: ${{ env.SRC }}/*.sfc
